### ISSUE TITLE
Security Issue (PostgreSQL)

### ISSUE THREAD

**Issue by ousamabenyounes** [sahilsunny/ogo#1]
Hi SahilSunny

ogo/src/main/java/com/sahilsunny/ogo/dao/SignupDao.java file has been compromised and your login/pwd are now visible on this this project
to remove it from your history:
https://help.github.com/articles/removing-sensitive-data-from-a-repository/

Change your login/pwd on all your projects...

Hope this will help you :)

**Comment by sahilsunny** [comment]
Thank you for pointing that out. But I am deploying to Heroku by linking it with GitHub. So if I removed that file. My app won't connect to the database. I relied on this method because deploying directly to Heroku was so slow. Is there any solution? such that I can still use GitHub for deploying. Like, hiding sensitive data from Github?

**Comment by sahilsunny** [comment]
@ousamabenyounes Thank you for providing me with this crucial info. I have reverted my commits to the state where my app's credentials are not exposed and created a new commit which avoids credentials being hard coded into code. Now my app relies on environment variables for credentials.

**Comment by ousamabenyounes** [comment]
@sahilsunny Really happy to see you removed your credential from your github project...
I think you also changed those credentials on your PostgreSql Database :)
Hackers track login / pwd on open source projects...I am working on this subject, and I'm always happy to see that those recommandations helped other developers...
We are human and we all make mistakes and what is really nice on github is that we can work together, improve our work together.

Good luck for your project and Have a nice day :)
